[package]
name = "crypto_symmetric"
version = "0.0.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"

[dependencies]
generic-array = "0.5"
crypto_buffers = {path = "../crypto-buffers"}
