[package]
name = "ripemd160"
version = "0.0.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"

[dependencies]
byte-tools = "0.1"
digest = "0.1"
digest-buffer = "0.1"
generic-array = "0.5"

[dev-dependencies]
crypto-tests = "0.1"
