[package]
name = "crypto_buffers"
version = "0.0.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"

[dependencies]
crypto_bytes = {path = "../crypto-bytes", default-features = false}
