[package]
name = "whirlpool"
version = "0.1.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "Whirlpool hash function"
documentation = "https://docs.rs/whirlpool"
repository = "https://github.com/RustCrypto/rust-crypto-decoupled"
keywords = ["crypto", "whirlpool", "hash", "digest"]

[dependencies]
byte-tools = "0.1"
digest = "0.1"
digest-buffer = "0.1"
generic-array = "0.5"

[dev-dependencies]
crypto-tests = "0.1"
