max_width = 80
ideal_width = 80
fn_call_width = 80
force_explicit_abi = false
fn_single_line = true
fn_args_density = "Compressed"
match_block_trailing_comma = true
normalize_comments = false
write_mode = "overwrite"
