[package]
name = "crypto_mac"
version = "0.0.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"

[dependencies]
generic-array = "0.5"
crypto-ops = "0.1"
byte-tools = "0.1"
digest = {path="../digest"}
