[package]
name = "blowfish"
version = "0.0.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"

[dependencies]
generic-array = "0.5"
byte-tools = "0.1"
crypto_symmetric = {path = "../../utils/crypto-symmetric"}

[features]
bcrypt = []