[package]
name = "blockmodes"
version = "0.0.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"

[dependencies]
crypto_symmetric = {path = "../crypto-symmetric"}
crypto_bytes = {path = "../crypto-bytes"}
crypto_buffers = {path = "../crypto-buffers"}
